/**
 * KOCOM CS - AJAX Gateway Specification
 * Extracted from: kocom_new_ip/html/ajax_proc.php, ajax_proc1.php, ajax_proc_mysql.php
 * Analysis date: 2026-04-15
 *
 * DB conventions:
 *   $MASTER_DB  = Oracle main schema (holds CS*, AS*, 자유게시판, QA게시판, 공지게시판,
 *                 자료게시판, 쪽지게시판, 대리점, STD_SMS, ACCESS_GRADE,
 *                 SMSMESSAGE_OFTEN, 기사메모, 전달사항, 처리담당자 ...)
 *   $mysql_DB   = "Xline5" MySQL schema (xline_agent_list, xline_callback, cti_call_log)
 *
 * GLOBAL SECURITY ISSUES (affect nearly ALL actions):
 *   - RAW string concatenation of $_REQUEST into SQL  -> SQL Injection in ~100% of queries
 *   - No CSRF token validation
 *   - No per-action authorization (only some rely on $_SESSION['user_id'])
 *   - Uses deprecated mysql_* functions in ajax_proc_mysql.php
 *   - iconv EUC-KR -> UTF-8 assumes a fixed client charset
 *   - Uses $_REQUEST (accepts both GET & POST) for state-changing ops => CSRF exploitable
 */
window.AJAX_SPECS = {
  meta: {
    analyzedAt: "2026-04-15",
    masterDb: "Oracle ($MASTER_DB)",
    secondaryDb: "MySQL (Xline5)",
    totalFiles: 3,
    totalActions: 88,
    totalSqlStatements: 150,
    riskSummary: {
      critical: "SQL Injection is systemic - every action concatenates $_REQUEST into SQL",
      high: "Uses $_REQUEST (GET+POST) for DML => CSRF possible",
      medium: "ajax_proc_mysql.php uses deprecated mysql_* API (removed in PHP7)",
      low: "Most handlers lack per-action RBAC; reliant on session existence only"
    }
  },

  ajax_proc: {
    file: "kocom_new_ip/html/ajax_proc.php",
    totalLines: 2203,
    entry: "switch($mode) on $_REQUEST['mode']",
    globals: ["$_REQUEST[mode]","$_REQUEST[idx]","$_REQUEST[umode]","$_REQUEST[chk]","$_SESSION[user_id]","$_SESSION[user_group]","$MASTER_DB"],
    actions: [
      { name:"my_info", line:11, purpose:"내정보(사원) 수정 - 이름/비밀번호/전화번호",
        params:["useridx","uNAME","pass1","tel1","tel2"],
        sql:"UPDATE CS사원 SET 사원명=?,비밀번호=?,전화번호1=?,전화번호2=? WHERE 사원번호=?",
        tables:["CS사원"], output:{type:"text",format:"ok | false"},
        calledBy:["my_info.php:62"],
        security:{risk:"critical", issues:["비밀번호 평문 저장","SQL Injection(모든 파라미터)","pass1이 GET으로도 전달 가능"]}},
      { name:"admin_user_del", line:30, purpose:"직원 퇴사/재직 전환",
        params:["idx","umode"],
        sql:"UPDATE CS사원 SET 현재사원여부=?, 종료일=SYSDATE WHERE 사원번호=?",
        tables:["CS사원"], output:{type:"text",format:"ok | false"},
        calledBy:["admin_user_list.php","admin_user_mode.php"],
        security:{risk:"high", issues:["SQL Injection","권한체크 없음(세션만 신뢰)"]}},
      { name:"user_id_check", line:39, purpose:"사원 아이디 중복 확인",
        params:["userid"],
        sql:"SELECT COUNT(*) FROM CS사원 WHERE 사원번호=?",
        tables:["CS사원"], output:{type:"text",format:"id^ok | id^false"},
        calledBy:["admin_user_mode.php"],
        security:{risk:"low", issues:["SQLi(SELECT만)","아이디 존재성 정보 노출"]}},
      { name:"user_passwd_change", line:50, purpose:"비밀번호 '999999' 초기화",
        params:["idx"],
        sql:"UPDATE CS사원 SET 비밀번호='999999' WHERE 사원번호=?",
        tables:["CS사원"], output:{type:"text",format:"ok | false"},
        calledBy:["admin_user_list.php"],
        security:{risk:"critical", issues:["누구나 사원 비밀번호를 999999로 초기화 가능(권한체크 부재)","평문 비밀번호"]}},
      { name:"admin_offmanager_del", line:59, purpose:"업체 담당자 삭제",
        params:["idx"],
        sql:"DELETE FROM CS담당자 WHERE 일련번호=?",
        tables:["CS담당자"], output:{type:"text",format:"ok | false"},
        calledBy:["admin_offmanager_list.php"],
        security:{risk:"high", issues:["SQL Injection","권한체크 없음"]}},
      { name:"admin_audit", line:70, purpose:"대행료 지급검정: 승인/취소/부적합 (umode=TO/T/F/C)",
        params:["where","umode","chk"],
        sql:"UPDATE CS처리 SET 결재여부=?,결재사원=?,결재일=sysdate WHERE 처리번호 IN(...)",
        tables:["CS처리","CS접수"], output:{type:"text",format:"ok^메시지"},
        calledBy:["admin_audit_list.php"],
        security:{risk:"critical", issues:["where 절이 그대로 SQL에 삽입됨 (임의 WHERE)","대량 데이터 수정 가능"]}},
      { name:"admin_audit_apply", line:120, purpose:"대행료 지급검정 적용(결재적용=1)",
        params:["where","umode","chk"],
        sql:"UPDATE CS처리 SET 결재적용='1',적용사원=?,적용일=sysdate WHERE ...",
        tables:["CS처리","CS접수"], output:{type:"text",format:"ok^메시지"},
        calledBy:["admin_audit_list_apply.php"],
        security:{risk:"critical", issues:["where 파라미터 SQL 삽입"]}},
      { name:"forum_free_count", line:150, purpose:"자유게시판 조회수 증가 + 반환",
        params:["idx"], sql:"UPDATE 자유게시판 SET 조회수=조회수+1 WHERE 글번호=?",
        tables:["자유게시판"], output:{type:"text",format:"count^idx^cnt"},
        calledBy:["forum_free_list.php","forum_free_mode.php"],
        security:{risk:"medium", issues:["SQLi"]}},
      { name:"forum_free_del", line:157, purpose:"자유게시판 글(스레드) 삭제 + 첨부파일 unlink(최대5개)",
        params:["idx"], sql:"DELETE FROM 자유게시판 WHERE 참조글번호=? AND 단계 LIKE ?%",
        tables:["자유게시판"], output:{type:"text",format:"del_ok | del_false"},
        calledBy:["forum_free_list.php","forum_free_mode.php"],
        security:{risk:"high", issues:["SQLi","작성자 권한 확인 없음 - 타인 글도 삭제 가능"]}},
      { name:"forum_free_file_del", line:173, purpose:"자유게시판 개별 첨부파일 삭제(파일1~5)",
        params:["idx","filenm"],
        sql:"UPDATE 자유게시판 SET 파일N=null WHERE 글번호=?",
        tables:["자유게시판"], output:{type:"text",format:"del_ok | del_false"},
        calledBy:["forum_free_mode.php"],
        security:{risk:"high", issues:["filenm이 SQL 컬럼명으로 직접 삽입됨 → SQL Injection via column","작성자 권한 미검사"]}},
      { name:"forum_qna_count", line:187, purpose:"Q&A 조회수 증가",
        params:["idx"], sql:"UPDATE QA게시판 SET 조회수=조회수+1 WHERE 글번호=?",
        tables:["QA게시판"], output:{type:"text",format:"count^idx^cnt"},
        calledBy:["forum_qna_list.php","forum_qna_mode.php"], security:{risk:"medium",issues:["SQLi"]}},
      { name:"forum_qna_del", line:194, purpose:"Q&A 스레드 삭제 + 첨부파일 제거",
        params:["idx"], sql:"DELETE FROM QA게시판 WHERE 참조글번호=? AND 단계 LIKE ?%",
        tables:["QA게시판"], output:{type:"text",format:"del_ok | del_false"},
        calledBy:["forum_qna_mode.php"], security:{risk:"high",issues:["SQLi","권한 미검사"]}},
      { name:"forum_qna_file_del", line:210, purpose:"Q&A 첨부파일 개별 삭제",
        params:["idx","filenm"], sql:"UPDATE QA게시판 SET 파일N=null WHERE 글번호=?",
        tables:["QA게시판"], output:{type:"text",format:"del_ok | del_false"},
        calledBy:["forum_qna_mode.php"], security:{risk:"high",issues:["컬럼명 SQLi"]}},
      { name:"forum_notice_count", line:224, purpose:"공지 조회수 증가",
        params:["idx"], sql:"UPDATE 공지게시판 SET 조회수=조회수+1 WHERE 글번호=?",
        tables:["공지게시판"], output:{type:"text",format:"count^idx^cnt"},
        calledBy:["forum_notice_list.php","forum_notice_mode.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"forum_notice_del", line:231, purpose:"공지 삭제 + 파일1~2 unlink",
        params:["idx"], sql:"DELETE FROM 공지게시판 WHERE 글번호=?",
        tables:["공지게시판"], output:{type:"text",format:"del_ok | del_false"},
        calledBy:["forum_notice_mode.php"],security:{risk:"high",issues:["SQLi","권한 미검사"]}},
      { name:"forum_notice_file_del", line:243, purpose:"공지 첨부파일 개별 삭제",
        params:["idx","filenm"], sql:"UPDATE 공지게시판 SET 파일N=null WHERE 글번호=?",
        tables:["공지게시판"], output:{type:"text",format:"del_ok | del_false"},
        calledBy:["forum_notice_mode.php"], security:{risk:"high",issues:["컬럼명 SQLi"]}},
      { name:"forum_pds_count", line:257, purpose:"자료실 조회수 증가",
        params:["idx"], sql:"UPDATE 자료게시판 SET 조회수=조회수+1 WHERE 글번호=?",
        tables:["자료게시판"], output:{type:"text",format:"count^idx^cnt"},
        calledBy:["forum_pds_list.php","forum_pds_mode.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"forum_pds_del", line:265, purpose:"자료실 삭제 + 파일1~9 unlink",
        params:["idx"], sql:"DELETE FROM 자료게시판 WHERE 글번호=?",
        tables:["자료게시판"], output:{type:"text",format:"del_ok | del_false"},
        calledBy:["forum_pds_mode.php"],security:{risk:"high",issues:["SQLi"]}},
      { name:"forum_pds_file_del", line:278, purpose:"자료실 첨부 개별 삭제 (중복정의됨: L318에서 재선언 → PHP switch 첫 case 우선)",
        params:["idx","filenm"], sql:"UPDATE 자료게시판 SET 파일N=null WHERE 글번호=?",
        tables:["자료게시판"], output:{type:"text",format:"del_ok | del_false"},
        calledBy:["forum_pds_mode.php"],
        security:{risk:"high",issues:["컬럼명 SQLi","duplicate case 정의(L318)로 쪽지 파일 삭제 로직이 dead code"]}},
      { name:"forum_memo_count", line:292, purpose:"쪽지 수신확인 처리(수신확인=1, 수신일=SYSDATE)",
        params:["idx"], sql:"UPDATE 쪽지게시판 SET 수신확인=1,수신일=(CASE WHEN 수신확인=0 THEN SYSDATE ELSE 수신일 END) WHERE 글번호=?",
        tables:["쪽지게시판"], output:{type:"text",format:"count^idx"},
        calledBy:["forum_memo_list.php","forum_memo_mode.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"forum_memo_del", line:298, purpose:"쪽지 소프트 삭제(발신인/수신인 플래그)",
        params:["idx"], sql:"UPDATE 쪽지게시판 SET 발신인DEL='Y'|수신인DEL='Y' WHERE 글번호=?",
        tables:["쪽지게시판"], output:{type:"text",format:"del_ok | del_false"},
        calledBy:["forum_memo_mode.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"admin_centermanager_file_del", line:331, purpose:"대리점 약도(이미지) 삭제",
        params:["idx"], sql:"UPDATE 대리점 SET 약도=null WHERE 대리점코드=?",
        tables:["대리점"], output:{type:"text",format:"del_ok | del_false"},
        calledBy:["admin_centermanager_mode.php"],security:{risk:"medium",issues:["SQLi","파일시스템 unlink"]}},
      { name:"admin_centermanager_del", line:342, purpose:"대리점 삭제 + 약도 파일 unlink",
        params:["idx"], sql:"DELETE FROM 대리점 WHERE 대리점코드=?",
        tables:["대리점"], output:{type:"text",format:"ok | false"},
        calledBy:["admin_centermanager_list.php"],security:{risk:"high",issues:["SQLi","권한 미검사"]}},
      { name:"sms_resend", line:354, purpose:"SMS 재발송 (EUC-KR→UTF-8 인코딩). MMS/SMS 자동선택(80자 기준)",
        params:["reciever","callback","sender"],
        sql:"INSERT INTO STD_SMS(cmp_msg_id,cmp_usr_id,odr_fg,msg_gb,wrt_dttm,snd_dttm,sms_gb,used_cd,rcv_phn_id,callback,expire_val,sms_st,rslt_val,snd_msg,rsrvd_id) VALUES(...)",
        tables:["STD_SMS"], output:{type:"text",format:"ok | false"},
        calledBy:["popup_sms_list.php:159"],
        security:{risk:"critical",issues:["SMS 스팸/피싱 악용 가능","SQL Injection in message","callback 번호 변조"]}},
      { name:"admin_code_error", line:411, purpose:"장애코드 입력/수정 (대메뉴/소메뉴 분기)",
        params:["stat","idx","codeName","bCODE"],
        sql:"INSERT INTO CS장애구분(장애코드,장애명,상위코드,사용여부)... | UPDATE CS장애구분 SET 장애명=? WHERE 장애코드=?",
        tables:["CS장애구분"], output:{type:"text",format:"ok^no^msg | exists^^msg | false^^msg"},
        calledBy:["admin_code_error_list.php:95-96"],security:{risk:"medium",issues:["SQLi","관리자 권한 미검사"]}},
      { name:"admin_code_error_useyn", line:473, purpose:"장애코드 사용여부 토글",
        params:["idx","bcode","bstat","stat"],
        sql:"UPDATE CS장애구분 SET 사용여부=? WHERE 장애코드=? OR 상위코드=?",
        tables:["CS장애구분"], output:{type:"text",format:"use_ok | use_false"},
        calledBy:["admin_code_error_list.php:102"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"admin_code_repair", line:496, purpose:"수리코드 입력/수정 (장애코드와 동일 로직)",
        params:["stat","idx","codeName","bCODE"],
        sql:"INSERT/UPDATE CS수리구분",
        tables:["CS수리구분"], output:{type:"text",format:"ok^... | exists^^..."},
        calledBy:["admin_code_repair_list.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"admin_code_repair_useyn", line:558, purpose:"수리코드 사용여부 토글",
        params:["idx","bcode","bstat","stat"],
        sql:"UPDATE CS수리구분 SET 사용여부=? WHERE 수리코드=? OR 상위코드=?",
        tables:["CS수리구분"], output:{type:"text",format:"use_ok | use_false"},
        calledBy:["admin_code_repair_list.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"admin_code_reason", line:582, purpose:"원인코드 입력/수정",
        params:["stat","idx","codeName","bCODE"],
        sql:"INSERT/UPDATE CS원인구분",
        tables:["CS원인구분"], output:{type:"text",format:"ok^... | exists^^..."},
        calledBy:["admin_code_reason_list.php"],security:{risk:"medium",issues:["SQLi","소메뉴 검증 쿼리에 '수리명' 오타 버그(항상 0건)"]}},
      { name:"admin_code_reason_useyn", line:644, purpose:"원인코드 사용여부 토글",
        params:["idx","bcode","bstat","stat"],
        sql:"UPDATE CS원인구분 SET 사용여부=? WHERE 원인코드=? OR 상위코드=?",
        tables:["CS원인구분"], output:{type:"text",format:"use_ok | use_false"},
        calledBy:["admin_code_reason_list.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"admin_scene_del", line:668, purpose:"현장(아파트) 삭제 - 품목 없으면 현장만, 있으면 품목+현장 삭제",
        params:["idx"],
        sql:"DELETE FROM CS현장품목 WHERE 아파트코드=?; DELETE FROM CS현장 WHERE 아파트코드=?",
        tables:["CS현장","CS현장품목"], output:{type:"text",format:"ok | false"},
        calledBy:["admin_scene_list.php","popup_scene_list.php","pop_admin_scene_list.php"],
        security:{risk:"high",issues:["SQLi","대량삭제 가능","권한 미검사"]}},
      { name:"admin_scene_detail_del", line:687, purpose:"현장 품목 1건 삭제",
        params:["idx"], sql:"DELETE FROM CS현장품목 WHERE 일련번호=?",
        tables:["CS현장품목"], output:{type:"text",format:"ok | false"},
        calledBy:["admin_scene_mode.php","admin_scene_mode1.php","popup_scene_mode.php"],security:{risk:"high",issues:["SQLi"]}},
      { name:"happycall_reset", line:698, purpose:"해피콜 상태 초기화(3 완료건 제외 NULL로)",
        params:["sday","eday","keyfield","centerName","pay_gbn"],
        sql:"UPDATE CS처리 SET 해피콜상태=null WHERE nvl(해피콜상태,0)!='3' AND [동적where]",
        tables:["CS처리"], output:{type:"text",format:"ok | false"},
        calledBy:["receipt_happycall_list.php"],
        security:{risk:"critical",issues:["센터명/유상여부 등 모든 필터가 SQL 직결","대량 데이터 변조"]}},
      { name:"happycall_accept", line:723, purpose:"해피콜 대상자 무작위 추출(dbms_random) - 지점별 비율($rate)",
        params:["sday","eday","keyfield","centerName","pay_gbn"],
        sql:"UPDATE CS처리 SET 해피콜상태='2' WHERE 처리번호 IN(random sample)",
        tables:["CS처리"], output:{type:"text",format:"accept_ok | accept_false"},
        calledBy:["receipt_happycall_list.php:98"],
        security:{risk:"critical",issues:["SQLi","$rate 미정의(버그, NULL)","N+1 쿼리(루프 내 UPDATE)"]}},
      { name:"happy_update", line:771, purpose:"해피콜 확인 저장(만족등급/고객의견/확인고객명)",
        params:["oNAME","score","memo","oDATE","idx"],
        sql:"UPDATE CS처리 SET 해피콜상태='3',확인여부='Y',확인사원=?,확인고객명=?,만족등급=?,고객의견=?,확인일=TO_DATE(?,'YYYY-MM-DD') WHERE 처리번호=?",
        tables:["CS처리"], output:{type:"text",format:"ok | false"},
        calledBy:["popup_happycall.php:71-74","popup_satisfaction.php:73-76"],
        security:{risk:"medium",issues:["SQLi"]}},
      { name:"callback_complete", line:803, purpose:"(주석처리됨) 콜백 완료 - MySQL xline_callback - 실제로는 ajax_proc_mysql.php로 이관",
        params:["idx","agent_id"],
        sql:"(commented out) UPDATE cti_callback SET state=2 WHERE seq_no=?",
        tables:["(cti_callback)"], output:{type:"text",format:"ok | exists"},
        calledBy:["(legacy)"],security:{risk:"info",issues:["코드 주석처리됨 - ajax_proc_mysql.php 사용"]}},
      { name:"callback_uncompleted", line:816, purpose:"(주석처리) 콜백 재요청", params:["idx"], sql:"(commented)", tables:[], output:{type:"text",format:"ok | exists"}, calledBy:[], security:{risk:"info",issues:["코드 주석처리"]}},
      { name:"callback_complete_with", line:827, purpose:"(주석처리) 복수 콜백 완료", params:["idx"], sql:"(commented)", tables:[], output:{type:"text",format:"ok | exists"}, calledBy:[], security:{risk:"info",issues:["코드 주석처리"]}},
      { name:"memual_delete", line:848, purpose:"매뉴얼 삭제 + 첨부파일 unlink",
        params:["idx"], sql:"DELETE FROM CS매뉴얼 WHERE 일련번호=?",
        tables:["CS매뉴얼"], output:{type:"text",format:"ok | false"},
        calledBy:["receipt_menual_list.php","receipt_menual_list_link.php","receipt_menual_mode.php"],security:{risk:"high",issues:["SQLi"]}},
      { name:"memo_delete", line:863, purpose:"특이사항 1건 삭제",
        params:["idx"], sql:"DELETE FROM CS특이사항 WHERE 일련번호=?",
        tables:["CS특이사항"], output:{type:"text",format:"ok | false"},
        calledBy:["receipt_memo_list.php"],security:{risk:"high",issues:["SQLi","권한 미검사"]}},
      { name:"ERRORSEL", line:873, purpose:"장애 소분류 SELECT 옵션 로드 (대분류→소분류)",
        params:["val","form","err2"],
        sql:"SELECT 장애코드,장애명 FROM CS장애구분 WHERE 상위코드=? AND 사용여부='Y'",
        tables:["CS장애구분"], output:{type:"text",format:"mode^기본텍스트@||name@code||... (파이프구분)"},
        calledBy:["receipt.php","receipt_year.php","resolve_year_mode.php"],
        security:{risk:"low",issues:["SQLi(SELECT)"]}},
      { name:"REPAIRSEL", line:895, purpose:"처리(수리) 소분류 SELECT 로드",
        params:["val","form","rc_2"],
        sql:"SELECT 수리코드,수리명 FROM CS수리구분 WHERE 상위코드=? AND 사용여부='Y' ORDER BY 수리명",
        tables:["CS수리구분"], output:{type:"text",format:"REPAIRSEL^...@||"},
        calledBy:["popup_svc.php","popup_svc1.php","svc_list.php","resolve_year_mode.php"],security:{risk:"low",issues:["SQLi"]}},
      { name:"CAUSESEL", line:916, purpose:"원인 소분류 SELECT 로드",
        params:["val","form","cs_2"],
        sql:"SELECT 원인코드,원인명 FROM CS원인구분 WHERE 상위코드=? AND 사용여부='Y'",
        tables:["CS원인구분"], output:{type:"text",format:"CAUSESEL^...@||"},
        calledBy:["popup_svc.php","popup_svc1.php","svc_list.php"],security:{risk:"low",issues:["SQLi"]}},
      { name:"SEL_AGENCY", line:937, purpose:"지점별 처리기사 옵션 로드 (텍스트 포맷)",
        params:["val","form"],
        sql:"SELECT 사원번호,사원명 FROM CS사원 WHERE 지점코드=? AND 현재사원여부='Y'",
        tables:["CS사원"], output:{type:"text",format:"^name@code||..."},
        calledBy:["receipt.php","receipt_year.php","popup_svc.php"],security:{risk:"low",issues:["SQLi"]}},
      { name:"SEL_AGENCY1", line:953, purpose:"지점별 처리기사 옵션 로드 (JSON)",
        params:["val","form"],
        sql:"SELECT 사원번호,사원명 FROM CS사원 WHERE 지점코드=? AND 현재사원여부='Y'",
        tables:["CS사원"], output:{type:"json",format:"[{charge_code,charge_name}]"},
        calledBy:["receipt_year_mode.php","resolve_year_mode.php"],security:{risk:"low",issues:["SQLi"]}},
      { name:"ZIP_SELECT", line:972, purpose:"접수 우편번호→담당지점/담당기사 자동선택",
        params:["zip","form"],
        sql:"SELECT 담당사원,구간구분 FROM 처리담당자 WHERE 지역코드=SUBSTR(?,0,3); SELECT ... FROM CS사원 JOIN AS지점",
        tables:["처리담당자","CS사원","AS지점"],
        output:{type:"text",format:"ZIP_SELECT^지점코드|사원|지점명|전화|사원명|구간"},
        calledBy:["receipt.php:320","receipt_year.php:178","receipt.php20170724"],security:{risk:"low",issues:["SQLi"]}},
      { name:"ZIP_SELECT1", line:993, purpose:"연차접수 우편번호 - 지점코드 + u+담당사원",
        params:["zip","form"],
        sql:"SELECT 담당사원,구간구분 FROM 처리담당자 WHERE 지역코드=...",
        tables:["처리담당자","CS사원","AS지점"],
        output:{type:"text",format:"ZIP_SELECT1^지점코드|u담당사원"},
        calledBy:["receipt_year_mode.php:272"],security:{risk:"low",issues:["SQLi"]}},
      { name:"ZIP_SELECT_i", line:1008, purpose:"현장관리 우편번호로 담당지점/사원/사원번호 선택",
        params:["zip","form"],
        sql:"동일 처리담당자→CS사원 조인",
        tables:["처리담당자","CS사원","AS지점"],
        output:{type:"text",format:"ZIP_SELECT_i^지점코드|담당사원|지점명|전화|사원명|사원번호"},
        calledBy:["admin_scene_mode.php","admin_scene_mode1.php","popup_scene_mode.php"],security:{risk:"low",issues:["SQLi"]}},
      { name:"custMOD", line:1029, purpose:"고객정보 수정",
        params:["custNAME","addr1","addr2","custTEL","custCELL","zip","apt_no","custNUM"],
        sql:"UPDATE CS고객정보 SET 고객명=?,집전화=?,휴대폰=?,우편번호=?,주소=?,상세주소=?,아파트코드=? WHERE 고객번호=?",
        tables:["CS고객정보"], output:{type:"text",format:"custMOD^msg"},
        calledBy:["receipt.php","receipt_year.php"],security:{risk:"high",issues:["SQLi","개인정보(PII) 변경 권한 미검사"]}},
      { name:"custINS", line:1052, purpose:"고객정보 신규 등록 (SEQ.NEXTVAL)",
        params:["custNAME","addr1","addr2","custTEL","custCELL","zip","apt_no"],
        sql:"INSERT INTO CS고객정보(고객번호,고객명,집전화,휴대폰,우편번호,주소,상세주소,아파트코드,등록자) VALUES(CS고객정보_고객번호_SEQ.NEXTVAL,...)",
        tables:["CS고객정보"], output:{type:"text",format:"custMOD^msg"},
        calledBy:["receipt.php","receipt_year.php"],security:{risk:"high",issues:["SQLi","PII 등록"]}},
      { name:"store_confirm", line:1078, purpose:"자재신청 승인(접수여부=Y)",
        params:["idx"],
        sql:"UPDATE CS자재신청 SET 접수여부='Y',접수사원=?,접수일=sysdate WHERE 신청번호=? AND 접수여부='N' AND 회사=?",
        tables:["CS자재신청"], output:{type:"text",format:"ok^msg"},
        calledBy:["store_request.php","store_request_release.php"],security:{risk:"medium",issues:["SQLi","항상 ok 반환(res 미체크)"]}},
      { name:"store_confirm2", line:1090, purpose:"자재출고 승인(출고승인=Y)",
        params:["idx"],
        sql:"UPDATE CS자재출고 SET 출고승인='Y',승인사원=?,승인일=sysdate WHERE 출고번호=? AND 출고승인='N' AND 회사=?",
        tables:["CS자재출고"], output:{type:"text",format:"ok^msg"},
        calledBy:["store_price_list.php","store_price_release.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"receipt_m_accept", line:1102, purpose:"모바일 접수 개별 승인",
        params:["idx"],
        sql:"UPDATE CS접수 SET 승인상태='Y',승인자=?,승인일시=sysdate WHERE 접수번호=?",
        tables:["CS접수"], output:{type:"text",format:"ok | false"},
        calledBy:["receipt_m_list.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"receipt_m_select_accept", line:1117, purpose:"모바일 접수 다중 선택 승인(|| 구분)",
        params:["idx"],
        sql:"(루프) UPDATE CS접수 SET 승인상태='Y' WHERE 접수번호=?",
        tables:["CS접수"], output:{type:"text",format:"ok | false"},
        calledBy:["receipt_m_list.php"],security:{risk:"medium",issues:["SQLi","N+1"]}},
      { name:"tk_status", line:1142, purpose:"TK(안전점검) 상태 완료처리",
        params:["idx"],
        sql:"UPDATE CS현장 SET TK상태='Y',TK수정일=sysdate,TK수정자=? WHERE 아파트코드=?",
        tables:["CS현장"], output:{type:"text",format:"ok | false"},
        calledBy:["receipt_tk_main_list.php:155"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"store_release", line:1158, purpose:"자재신청품목 소프트삭제(삭제여부=Y)",
        params:["idx","tr"],
        sql:"UPDATE CS자재신청품목 SET 삭제여부='Y',수정사원=?,수정일자=sysdate WHERE 신청일련번호=?",
        tables:["CS자재신청품목"], output:{type:"text",format:"del_ok^tr"},
        calledBy:["store_request_release.php:144","tdb_store_mode.php:123"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"store_release_update", line:1170, purpose:"자재 진행상황 변경",
        params:["idx","st1","st2"],
        sql:"UPDATE CS자재신청품목 SET 진행상황=?,수정사원=?,수정일자=sysdate WHERE 신청일련번호=?",
        tables:["CS자재신청품목"], output:{type:"text",format:"upd_ok^st2"},
        calledBy:["store_request_release.php:186"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"store_return_delete", line:1182, purpose:"자재반품 품목 소프트삭제",
        params:["idx","tr"],
        sql:"UPDATE CS자재신청품목 SET 삭제여부='Y' WHERE 신청번호=?",
        tables:["CS자재신청품목"], output:{type:"text",format:"del_ok^tr"},
        calledBy:["store_return_release.php","popup_return.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"store_return_update", line:1194, purpose:"자재 반납상태 변경 (4/5: 반납일 자동세팅)",
        params:["idx","st1","st2"],
        sql:"UPDATE CS자재신청품목 SET 반납상태=?,[반납일=sysdate,]수정사원=?,수정일자=sysdate WHERE 신청일련번호=?",
        tables:["CS자재신청품목"], output:{type:"text",format:"upd_ok^st2"},
        calledBy:["store_return_release.php","popup_return.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"tdb_etc_del", line:1214, purpose:"뇌전 기타내용 삭제",
        params:["idx","tr"], sql:"DELETE FROM CS뇌전기타목록 WHERE 일련번호=?",
        tables:["CS뇌전기타목록"], output:{type:"text",format:"del_ok^tr"},
        calledBy:["tdb_in_mode.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"tdb_etc_ins", line:1220, purpose:"뇌전 기타내용 추가",
        params:["idx","subject","content","tr"],
        sql:"INSERT INTO CS뇌전기타목록 VALUES(?,SEQ.nextval,?,?,sysdate,?)",
        tables:["CS뇌전기타목록"], output:{type:"text",format:"ins_ok^tr^subject^content^no"},
        calledBy:["tdb_in_mode.php"],security:{risk:"high",issues:["SQLi 가능(subject/content 이스케이프 없음)"]}},
      { name:"tdb_store_release_update", line:1228, purpose:"뇌전 자재 진행상황 변경",
        params:["idx","st1","st2"],
        sql:"UPDATE CS뇌전자재신청품목 SET 진행상황=? WHERE 신청일련번호=?",
        tables:["CS뇌전자재신청품목"], output:{type:"text",format:"upd_ok^idx"},
        calledBy:["tdb_store_release.php","tdb_store_mode.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"tdb_store_release", line:1239, purpose:"뇌전 자재 품목 소프트삭제",
        params:["idx","tr"],
        sql:"UPDATE CS뇌전자재신청품목 SET 삭제여부='Y' WHERE 신청일련번호=?",
        tables:["CS뇌전자재신청품목"], output:{type:"text",format:"del_ok^tr"},
        calledBy:["tdb_store_release.php","tdb_store_mode.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"tdb_return_update", line:1251, purpose:"뇌전 자재 반납상태 변경",
        params:["idx","st1"],
        sql:"UPDATE CS뇌전자재신청품목 SET 반납상태=? WHERE 신청일련번호=?",
        tables:["CS뇌전자재신청품목"], output:{type:"text",format:"upd_ok^idx"},
        calledBy:["tdb_return_release.php","tdb_return_ins_release.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"svcPayChange", line:1262, purpose:"유/무/유지보수 전환시 출장비 자동계산 (F_구간출장비추출/F_CS출장비추출)",
        params:["rno","cno","status","gugan"],
        sql:"SELECT F_구간출장비추출(구간구분,sysdate) FROM CS접수 WHERE 접수번호=?",
        tables:["CS접수","AS품목"], output:{type:"text",format:"svcPayChange^price"},
        calledBy:["popup_svc.php","popup_svc1.php","svc_list.php"],security:{risk:"low",issues:["SQLi"]}},
      { name:"jajea_price", line:1296, purpose:"자재 등급 변경시 소비자가 조회",
        params:["stype","pay_gbn","sno","sc"],
        sql:"SELECT 소비자가A|소비자가R|소비자유지보수가 FROM AS품목 WHERE 품번=?",
        tables:["AS품목"], output:{type:"text",format:"jajea_price^sc^price"},
        calledBy:["popup_svc.php","popup_svc1.php"],security:{risk:"medium",issues:["SQLi - pay_gbn/stype이 컬럼명 생성에 사용"]}},
      { name:"svc_reset", line:1310, purpose:"처리내역 완전삭제 (처리 + 처리부품)",
        params:["cno","rno"],
        sql:"DELETE FROM CS처리 WHERE 처리번호=?; DELETE FROM CS처리부품 WHERE 처리번호=?",
        tables:["CS처리","CS처리부품"], output:{type:"text",format:"reset^rno"},
        calledBy:["popup_svc.php","popup_svc1.php"],security:{risk:"high",issues:["SQLi","권한 미검사"]}},
      { name:"store_request_delete", line:1318, purpose:"자재신청 품목 삭제(신청번호+품번)",
        params:["req_no","idx"],
        sql:"DELETE FROM CS자재신청품목 WHERE 신청번호=? AND 품번=?",
        tables:["CS자재신청품목"], output:{type:"text",format:"(없음)"},
        calledBy:["store_request.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"store_request_nomal_delete", line:1326, purpose:"일반 자재신청 품목 삭제(동일 로직)",
        params:["req_no","idx"],
        sql:"DELETE FROM CS자재신청품목 WHERE 신청번호=? AND 품번=?",
        tables:["CS자재신청품목"], output:{type:"text",format:"(없음)"},
        calledBy:["store_request_nomal.php"],security:{risk:"medium",issues:["SQLi","duplicate of store_request_delete"]}},
      { name:"price_store", line:1335, purpose:"자재청구가 정산 프로시저 호출(P_CS자재청구가_등록2)",
        params:["sday","eday"],
        sql:"BEGIN P_CS자재청구가_등록2(?,?,?,sysdate,'10000');END; + UPDATE CS자재신청 SET 본사승인='1' ...",
        tables:["CS자재신청"], output:{type:"text",format:"price_ok"},
        calledBy:["store_price_list.php:71"],security:{risk:"high",issues:["SQLi via 날짜","저장프로시저 직접 호출","NLS_DATE_FORMAT 세션변경"]}},
      { name:"price_tdb", line:1368, purpose:"뇌전자재청구가 정산 프로시저(P_CS뇌전자재청구가_등록)",
        params:["rno","idx"],
        sql:"BEGIN P_CS뇌전자재청구가_등록(?,?,sysdate,'10000');END;",
        tables:["(프로시저)"], output:{type:"text",format:"ok^idx"},
        calledBy:["tdb_price_release.php","popup_tdb_price_modify.php"],security:{risk:"high",issues:["SQLi"]}},
      { name:"price_tdb_modify", line:1391, purpose:"뇌전 자재 등급/유무상별 반납·미반납 정산단가 재계산",
        params:["idx"],
        sql:"SELECT ... FROM CS뇌전자재신청품목 WHERE 신청번호=? → UPDATE SET 반납정산단가=?,미반납정산단가=? WHERE 신청일련번호=?",
        tables:["CS뇌전자재신청품목"], output:{type:"text",format:"ok_modify^idx"},
        calledBy:["popup_tdb_price_modify.php"],security:{risk:"medium",issues:["SQLi","N+1 UPDATE"]}},
      { name:"access_grade", line:1438, purpose:"권한(INS/UPD/DEL) 설정 - UPSERT",
        params:["grade","idx","ins","upd","del"],
        sql:"UPDATE ACCESS_GRADE SET INS_TF=?,UPD_TF=?,DEL_TF=? WHERE USER_LEVEL=? AND NO=? | INSERT INTO ACCESS_GRADE(...)",
        tables:["ACCESS_GRADE"], output:{type:"text",format:"grade"},
        calledBy:["admin_access_mode.php"],security:{risk:"critical",issues:["권한 자체를 수정하는 엔드포인트에 권한 체크 없음","SQLi"]}},
      { name:"receipt_memo_count", line:1460, purpose:"특이사항 조회수 증가",
        params:["idx"], sql:"UPDATE CS특이사항 SET 조회수=nvl(조회수,0)+1 WHERE 일련번호=?",
        tables:["CS특이사항"], output:{type:"text",format:"count^idx^cnt"},
        calledBy:["receipt_memo_list.php"],security:{risk:"low",issues:["SQLi"]}},
      { name:"search_model_name", line:1471, purpose:"품번→모델명(품명) 조회",
        params:["val","target"],
        sql:"SELECT 품명 FROM AS품목구성 A,AS품목 B WHERE A.모품번=B.품번 AND 품번=?",
        tables:["AS품목","AS품목구성"], output:{type:"text",format:"model_name^name^target"},
        calledBy:["popup_serial.php","svc_list.php"],security:{risk:"low",issues:["SQLi"]}},
      { name:"memo_next", line:1483, purpose:"기사메모 추가 (수동 PK MAX+1)",
        params:["m_no","m_time","memo","form"],
        sql:"INSERT INTO 기사메모(접수번호,접수일시,메모,메모번호,접수자) VALUES(?,TO_DATE(?),?,MAX+1,?)",
        tables:["기사메모"], output:{type:"text",format:"m_ok | m_false"},
        calledBy:["receipt.php:330","receipt_year.php:187","receipt_g_memo.php:142"],
        security:{risk:"high",issues:["SQLi","MAX+1 PK race condition(동시쓰기 중복키)"]}},
      { name:"memo_update", line:1506, purpose:"기사메모 내용 수정",
        params:["m_no","memo"],
        sql:"UPDATE 기사메모 SET 메모=? WHERE 메모번호=?",
        tables:["기사메모"], output:{type:"text",format:"m_up_ok | m_up_false"},
        calledBy:["receipt.php","receipt_g_memo.php"],security:{risk:"medium",issues:["SQLi","작성자 검증 없음"]}},
      { name:"memo_del", line:1521, purpose:"기사메모 삭제",
        params:["idx","form"], sql:"DELETE FROM 기사메모 WHERE 메모번호=?",
        tables:["기사메모"], output:{type:"text",format:"m_del_ok | m_del_false"},
        calledBy:["receipt.php","receipt_g_memo.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"message_next", line:1533, purpose:"연차접수 전달사항 추가",
        params:["s_no","m_time","message","id","form"],
        sql:"INSERT INTO 전달사항(접수번호,메시지,작성자,작성일자,순번) VALUES(?,?,?,TO_DATE(?),MAX+1)",
        tables:["전달사항"], output:{type:"text",format:"mm_ok | mm_false"},
        calledBy:["receipt_year.php","receipt_year_mode.php"],security:{risk:"high",issues:["SQLi","PK race","id 파라미터 신뢰(클라이언트 전달)"]}},
      { name:"message_update", line:1560, purpose:"전달사항 수정",
        params:["no","message","form"],
        sql:"UPDATE 전달사항 SET 메시지=? WHERE 순번=?",
        tables:["전달사항"], output:{type:"text",format:"up_ok | up_false"},
        calledBy:["receipt_year.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"message_delete", line:1576, purpose:"전달사항 삭제",
        params:["no","form"], sql:"DELETE FROM 전달사항 WHERE 순번=?",
        tables:["전달사항"], output:{type:"text",format:"mmm_ok | mmm_false"},
        calledBy:["receipt_year.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"search_cust_number", line:1635, purpose:"전화/휴대폰으로 고객번호/고객명 조회 (align_tel 적용)",
        params:["tel"],
        sql:"SELECT 고객번호,고객명 FROM CS고객정보 WHERE 집전화=? UNION ALL ... 휴대폰=? → 없으면 CS접수에서",
        tables:["CS고객정보","CS접수"], output:{type:"text",format:"cust_number^no^name"},
        calledBy:["receipt.php","receipt_year.php","popup_svc.php"],
        security:{risk:"high",issues:["PII 열거(enumeration)","SQLi","인증 최소검증"]}},
      { name:"tk_delete", line:1681, purpose:"TK(동) 설정 삭제 + 공용/세대 접수 삭제",
        params:["apt_no","dong","idx"],
        sql:"UPDATE CSTK설정 SET 삭제여부='Y'; DELETE FROM CSTK공용; DELETE FROM CSTK세대",
        tables:["CSTK설정","CSTK공용","CSTK세대"], output:{type:"text",format:"tk_del_ok | tk_del_false"},
        calledBy:["receipt_tk_setting.php:187"],
        security:{risk:"high",issues:["SQLi","RES2 대입 버그: query1 두번 실행(query2 대신)"]}},
      { name:"tk_delete_G", line:1704, purpose:"TK 공용 1건 삭제",
        params:["apt_no","dong","tkuser","gidx","idx"],
        sql:"UPDATE CSTK설정 SET 삭제여부='Y' ... AND 공용접수번호=?; DELETE FROM CSTK공용 WHERE 접수번호=?",
        tables:["CSTK설정","CSTK공용"], output:{type:"text",format:"tk_del_G_ok | tk_del_G_false"},
        calledBy:["popup_tk_G.php:162"],security:{risk:"high",issues:["SQLi"]}},
      { name:"tk_delete_S", line:1726, purpose:"TK 세대 1건 삭제",
        params:["apt_no","dong","tkuser","sidx","idx"],
        sql:"UPDATE CSTK설정 ... AND 세대접수번호=?; DELETE FROM CSTK세대 WHERE 접수번호=?",
        tables:["CSTK설정","CSTK세대"], output:{type:"text",format:"tk_del_S_ok | tk_del_S_false"},
        calledBy:["popup_tk_S.php","popup_tk_S_detail.php:103"],security:{risk:"high",issues:["SQLi"]}},
      { name:"tk_change", line:1749, purpose:"TK 담당지점/점검자 변경",
        params:["center","chargeName","idx"],
        sql:"UPDATE CS현장 SET TK담당지점=?,TK점검자=? WHERE 아파트코드=?; UPDATE CSTK설정 SET 점검자=?",
        tables:["CS현장","CSTK설정"], output:{type:"text",format:"tk_change_ok | tk_change_false"},
        calledBy:["receipt_tk_main_list.php","receipt_tk_setting.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"tk_line_delete_S", line:1768, purpose:"라인 단위 TK 세대 미완료건 일괄 삭제 (완료건·서명 있으면 차단)",
        params:["apt_no","dong","line"],
        sql:"SELECT count(*) WHERE 완료여부='Y' OR 성명파일/전유파일/공용파일 IS NOT NULL → UPDATE 삭제여부='Y'; DELETE CSTK세대 미완료",
        tables:["CSTK설정","CSTK세대"], output:{type:"text",format:"del_ok | del_false | tk_del_fail"},
        calledBy:["receipt_tk_setting.php"],security:{risk:"high",issues:["SQLi","WHERE OR 우선순위 의도 불일치"]}},
      { name:"tdb_end", line:1796, purpose:"뇌전 종료 처리 - 품목의 뇌전종료일=SYSDATE, 잔여 없으면 현장 뇌전유무=N",
        params:["rct_no"],
        sql:"UPDATE CS현장품목 SET 뇌전종료일=sysdate WHERE 접수번호=?; 조건부 UPDATE CS현장 SET 뇌전유무='N'",
        tables:["CS현장","CS현장품목"], output:{type:"text",format:"tdb_end_ok | tdb_end_false"},
        calledBy:["tdb_in_list.php","tdb_in_mode.php"],security:{risk:"medium",issues:["SQLi","$tdb_num 변수 잘못 사용(스칼라 아닌 SQL문 비교)"]}},
      { name:"tdb_change", line:1819, purpose:"뇌전접수 센터 변경",
        params:["rct_no","center"],
        sql:"UPDATE CS뇌전접수 SET 접수센터=? WHERE 접수번호=?",
        tables:["CS뇌전접수"], output:{type:"text",format:"tdb_change_ok | tdb_change_false"},
        calledBy:["tdb_in_list.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"parcel_next", line:1834, purpose:"배송방법(택배/방문) 및 송장번호/방문일자 설정",
        params:["parcel","type","visit","idx"],
        sql:"UPDATE CS자재신청 SET 송장번호=?,배송방법=?,방문일자=null | 방문일자=TO_DATE(?),배송방법=?,송장번호=null WHERE 신청번호=?",
        tables:["CS자재신청"], output:{type:"text",format:"parcel_ok/visit_ok/*_false"},
        calledBy:["store_request_release.php:285-288"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"expected_next", line:1862, purpose:"출고예정일 설정",
        params:["sid","expected"],
        sql:"UPDATE CS자재신청품목 SET 출고예정일=TO_DATE(?) WHERE 신청일련번호=?",
        tables:["CS자재신청품목"], output:{type:"text",format:"expected_ok | expected_false"},
        calledBy:["popup_serial.php:107"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"cancel_next", line:1877, purpose:"방문예약취소 코드 INSERT/UPDATE",
        params:["code","stat","codeName"],
        sql:"INSERT INTO CS방문예약취소 VALUES(LPAD(MAX+1,3,'0'),?,'Y') | UPDATE ... SET 예약취소명=? WHERE 취소코드=?",
        tables:["CS방문예약취소"], output:{type:"text",format:"cancel_insert_ok|*_false"},
        calledBy:["popup_visit_cancel.php:71"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"cancel_yn", line:1911, purpose:"방문예약취소 사용여부 토글",
        params:["idx","stat"],
        sql:"UPDATE CS방문예약취소 SET 사용여부=? WHERE 취소코드=?",
        tables:["CS방문예약취소"], output:{type:"text",format:"use_ok | use_false"},
        calledBy:["popup_visit_cancel.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"store_code_next", line:1930, purpose:"자재출고 등급코드 INSERT/UPDATE",
        params:["code","stat","codeName"],
        sql:"INSERT INTO CS자재출고등급 VALUES(MAX+1,?,'Y') | UPDATE 등급명=? WHERE 등급코드=?",
        tables:["CS자재출고등급"], output:{type:"text",format:"store_code_insert_ok|*_false"},
        calledBy:["popup_store_grade.php:71"],security:{risk:"medium",issues:["SQLi","PK race"]}},
      { name:"store_code_yn", line:1962, purpose:"자재출고등급 사용여부 토글",
        params:["idx","stat"],
        sql:"UPDATE CS자재출고등급 SET 사용여부=? WHERE 등급코드=?",
        tables:["CS자재출고등급"], output:{type:"text",format:"store_code_ok | store_code_false"},
        calledBy:["popup_store_grade.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"store_message", line:1981, purpose:"자재신청 본사→센터 메시지 저장",
        params:["message","idx"],
        sql:"UPDATE CS자재신청 SET 메시지=? WHERE 신청번호=?",
        tables:["CS자재신청"], output:{type:"text",format:"store_message_ok | *_false"},
        calledBy:["store_request_release.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"store_message_center", line:1995, purpose:"자재신청 센터→본사 요청메시지(신청내용) 저장",
        params:["r_message","idx"],
        sql:"UPDATE CS자재신청 SET 신청내용=? WHERE 신청번호=?",
        tables:["CS자재신청"], output:{type:"text",format:"store_r_message_ok | *_false"},
        calledBy:["store_request.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"return_renewal", line:2009, purpose:"시리얼 반납예정일 1개월 연장",
        params:["r_date","r_num","idx"],
        sql:"UPDATE CS시리얼 SET 반납예정일=ADD_MONTHS(?,1) WHERE 출고번호=?",
        tables:["CS시리얼"], output:{type:"text",format:"renuwal_ok | renewal_false"},
        calledBy:["store_return_release.php","tdb_return_release.php"],security:{risk:"medium",issues:["SQLi","반납연장횟수 기능 주석처리"]}},
      { name:"tdb_price_modify", line:2030, purpose:"뇌전자재 센터가 5종 수동 수정 + 금액초기화 플래그",
        params:["returnA","retreA","returnR","retreR","maintenance","user_id","idx"],
        sql:"UPDATE CS뇌전자재신청품목 SET 센터반납가A=?,센터미반납가A=?,센터반납가R=?,센터미반납가R=?,센터유지보수가=?,금액수정사원=?,금액초기화='1' WHERE 신청일련번호=?",
        tables:["CS뇌전자재신청품목"], output:{type:"text",format:"ok | false"},
        calledBy:["popup_tdb_price_modify.php"],security:{risk:"high",issues:["SQLi","user_id를 클라이언트에서 전달(신뢰금지)"]}},
      { name:"price_center_ok", line:2049, purpose:"자재신청 센터확인 플래그 1 처리",
        params:["idx"],
        sql:"UPDATE CS자재신청 SET 센터확인='1' WHERE 신청번호=?",
        tables:["CS자재신청"], output:{type:"text",format:"ok | false"},
        calledBy:["store_price_release.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"aff_add", line:2061, purpose:"지점 소속(상위센터) 설정",
        params:["center_name","aff_name"],
        sql:"UPDATE AS지점 SET 소속=? WHERE 지점코드=?",
        tables:["AS지점"], output:{type:"text",format:"ok | false"},
        calledBy:["popup_center_aff.php:67"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"aff_del", line:2075, purpose:"지점 소속 해제",
        params:["center_name","aff_name"],
        sql:"UPDATE AS지점 SET 소속=null WHERE 지점코드=?",
        tables:["AS지점"], output:{type:"text",format:"del_ok | false"},
        calledBy:["popup_center_aff.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"message_inup", line:2089, purpose:"자주쓰는 SMS 문구 INSERT/UPDATE",
        params:["code","stat","message"],
        sql:"INSERT INTO SMSMESSAGE_OFTEN(번호,내용,사용유무,비고) VALUES(MAX+1,?,'Y','') | UPDATE SET 내용=? WHERE 번호=?",
        tables:["SMSMESSAGE_OFTEN"], output:{type:"text",format:"insert_ok|update_ok|*_false"},
        calledBy:["popup_sms.php","popup_sms_list.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"message_use", line:2126, purpose:"자주쓰는 문구 사용유무 토글",
        params:["idx","stat"],
        sql:"UPDATE SMSMESSAGE_OFTEN SET 사용유무=? WHERE 번호=?",
        tables:["SMSMESSAGE_OFTEN"], output:{type:"text",format:"use_ok | use_false"},
        calledBy:["popup_sms.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"message_often_delete", line:2145, purpose:"자주쓰는 문구 삭제",
        params:["idx"], sql:"DELETE FROM SMSMESSAGE_OFTEN WHERE 번호=?",
        tables:["SMSMESSAGE_OFTEN"], output:{type:"text",format:"delete_ok | delete_false"},
        calledBy:["popup_sms.php"],security:{risk:"medium",issues:["SQLi"]}},
      { name:"tdb_in_delete", line:2157, purpose:"뇌전접수 + 관련 현장품목 DELETE",
        params:["idx"],
        sql:"DELETE FROM CS현장품목 WHERE 접수번호=?; DELETE FROM CS뇌전접수 WHERE 접수번호=?",
        tables:["CS현장품목","CS뇌전접수"], output:{type:"text",format:"del_ok | false"},
        calledBy:["tdb_in_list.php"],security:{risk:"high",issues:["SQLi","권한 미검사","트랜잭션 없음"]}}
    ]
  },

  ajax_proc1: {
    file: "kocom_new_ip/html/ajax_proc1.php",
    totalLines: 1214,
    note: "ajax_proc.php의 구버전(레거시). 동일/유사 액션 중복 보유. 주요 차이:",
    differences: [
      "admin_audit에서 'C'(부적합) 없음, apply 변형 없음",
      "forum_qna_* 액션 없음 (L118부터 바로 forum_free_count)",
      "receipt_m_accept, tk_* 액션들, tdb_* 액션들, cancel_next/yn, store_code_*, store_message*, return_renewal, tdb_price_modify, price_center_ok, aff_add/del, message_inup/use/often_delete, tdb_in_delete 등 최신 추가 액션 미존재",
      "search_cust_number 없음, parcel_next/expected_next 없음",
      "SEL_AGENCY1(JSON) 없음",
      "callback_* 3종이 실제 활성(ajax_proc.php에서는 주석)"
    ],
    commonActions: [
      "my_info","admin_user_del","user_id_check","user_passwd_change","admin_offmanager_del","admin_audit",
      "forum_free_count","forum_free_del","forum_free_file_del",
      "forum_notice_count","forum_notice_del","forum_notice_file_del",
      "forum_pds_count","forum_pds_del","forum_pds_file_del",
      "forum_memo_count","forum_memo_del",
      "admin_centermanager_file_del","admin_centermanager_del",
      "sms_resend","admin_code_error","admin_code_error_useyn","admin_code_repair","admin_code_repair_useyn",
      "admin_code_reason","admin_code_reason_useyn","admin_scene_del","admin_scene_detail_del",
      "happycall_reset","happycall_accept","happy_update",
      "callback_complete","callback_uncompleted","callback_complete_with",
      "memual_delete","memo_delete","ERRORSEL","REPAIRSEL","CAUSESEL","SEL_AGENCY",
      "ZIP_SELECT","custMOD","custINS","store_confirm","store_confirm2",
      "receipt_m_accept","receipt_m_select_accept","tk_status",
      "store_release","store_release_update","store_return_delete","store_return_update",
      "tdb_etc_del","tdb_etc_ins","tdb_store_release_update","tdb_store_release","tdb_return_update",
      "svcPayChange","jajea_price","svc_reset","store_request_delete","store_request_nomal_delete",
      "price_store","price_tdb","access_grade","receipt_memo_count"
    ],
    security:{risk:"critical", issues:["ajax_proc.php과 동일한 SQLi 구조","호출 참조가 남아 있어 구버전이 실제로 실행될 수 있음"]}
  },

  ajax_proc_mysql: {
    file: "kocom_new_ip/html/ajax_proc_mysql.php",
    totalLines: 116,
    note: "MySQL Xline5(콜백/CTI)용. 구식 mysql_* API 사용",
    connection: "mysql_select_db('Xline5' | 'cti')",
    actions: [
      { name:"user_yn", line:14, purpose:"xline 상담원 del_yn 토글(umode=Y/N)",
        params:["idx","umode"],
        sql:"UPDATE xline_agent_list SET del_yn=? WHERE agent_id=?",
        tables:["xline_agent_list"], output:{type:"text",format:"(출력 없음)"},
        calledBy:["admin_user_list.php(추정)"],security:{risk:"high",issues:["mysql_* 구식","SQLi"]}},
      { name:"callback_complete", line:21, purpose:"콜백 완료처리(state=2) + agent_id 기록",
        params:["idx","agent_id"],
        sql:"SELECT COUNT(*) FROM xline_callback WHERE uniq_id=?; UPDATE xline_callback SET state=2, agent_id=? WHERE uniq_id=?",
        tables:["xline_callback"], output:{type:"text",format:"ok | exists"},
        calledBy:["receipt_callback_list.php","main_list.php"],security:{risk:"high",issues:["mysql_*","SQLi"]}},
      { name:"callback_uncompleted", line:40, purpose:"콜백 미완료 복원(state=1, agent_id='')",
        params:["idx"],
        sql:"UPDATE xline_callback SET state=1, agent_id='' WHERE uniq_id=?",
        tables:["xline_callback"], output:{type:"text",format:"ok | exists"},
        calledBy:["receipt_callback_list.php"],security:{risk:"high",issues:["mysql_*","SQLi"]}},
      { name:"callback_complete_with", line:52, purpose:"다중 콜백 완료(idx='||cust-uniq||...')",
        params:["idx","agent_id"],
        sql:"UPDATE xline_callback SET state=2, agent_id=? WHERE (cust_id=? AND uniq_id=?) OR (...)",
        tables:["xline_callback"], output:{type:"text",format:"ok | exists"},
        calledBy:["receipt_callback_list.php"],security:{risk:"high",issues:["mysql_*","SQLi via idx 파싱"]}},
      { name:"nowcall", line:91, purpose:"오늘 요청수/상담수 집계(cti_call_log)",
        params:["(none - $_COOKIE['agent_id'] 사용)"],
        sql:"SELECT COUNT(*) FROM cti_call_log WHERE call_type='1' AND ivr_time>=? [AND agent_id=?]",
        tables:["cti_call_log"], output:{type:"text",format:"요청수:n상담수:n (EUC-KR 깨진 문자열)"},
        calledBy:["main_list.php(추정)"],security:{risk:"medium",issues:["$_COOKIE agent_id 신뢰 금지","mysql_*"]}}
    ]
  }
};
